// Code generated by cmd/reset. DO NOT EDIT.

package agent

import (
	"time"
)

func (r *MetricsBatch) Reset() {
	if r == nil {
		return
	}

	if resetter, ok := interface{}(&r.Timestamp).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		r.Timestamp = time.Time{}
	}
	r.MetricType = ""
	r.Values = r.Values[:0]
	clear(r.Labels)
	r.Count = 0
	r.IsActive = false
}
